version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - ineffassign
    - bodyclose
    - goconst
  disable:
    - errcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports