name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --verbose